// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHDySVEhQvJyGUNiwoCTkLzbZlizSa5I8',
    appId: '1:31260440309:web:8cf4cc3cd58c0dcd81b7bc',
    messagingSenderId: '31260440309',
    projectId: 'app-campeonato-pokemon',
    authDomain: 'app-campeonato-pokemon.firebaseapp.com',
    storageBucket: 'app-campeonato-pokemon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW5tORXXUL9aDvtiHyItzVibxkEf-W_Lo',
    appId: '1:31260440309:android:e0226ba61799bfdc81b7bc',
    messagingSenderId: '31260440309',
    projectId: 'app-campeonato-pokemon',
    storageBucket: 'app-campeonato-pokemon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNyvznz0oqwlNg0MaZdM-GtK7dOP1mYs',
    appId: '1:901204867240:ios:6a2413be8dcfeb4c9d2a9d',
    messagingSenderId: '901204867240',
    projectId: 'email-login-b6329',
    storageBucket: 'email-login-b6329.firebasestorage.app',
    iosBundleId: 'com.example.appP1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbNyvznz0oqwlNg0MaZdM-GtK7dOP1mYs',
    appId: '1:901204867240:ios:6a2413be8dcfeb4c9d2a9d',
    messagingSenderId: '901204867240',
    projectId: 'email-login-b6329',
    storageBucket: 'email-login-b6329.firebasestorage.app',
    iosBundleId: 'com.example.appP1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHDySVEhQvJyGUNiwoCTkLzbZlizSa5I8',
    appId: '1:31260440309:web:8cf4cc3cd58c0dcd81b7bc',
    messagingSenderId: '31260440309',
    projectId: 'app-campeonato-pokemon',
    authDomain: 'app-campeonato-pokemon.firebaseapp.com',
    storageBucket: 'app-campeonato-pokemon.firebasestorage.app',
  );

}